# Generated by Django 3.0.6 on 2020-06-05 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todoslist',
            name='completed',
        ),
        migrations.AddField(
            model_name='todoslist',
            name='datecompleted',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='todoslist',
            name='important',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='todoslist',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
