# Generated by Django 3.0.6 on 2020-06-06 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_todoslist_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoslist',
            name='memo',
            field=models.TextField(blank=True),
        ),
    ]
